/* CodeBreak Party - Supabase multiplayer */
const CONFIG = {
  SUPABASE_URL: "https://csudjixajhfsdjezedbl.supabase.co",
  SUPABASE_ANON_KEY: "sb_publishable_Xh1g88ix8BLOEsWJcw37Cw_QrHqMiO7"
};
const configured = !CONFIG.SUPABASE_URL.startsWith("PASTE_") && !CONFIG.SUPABASE_ANON_KEY.startsWith("PASTE_");
const sb = configured ? window.supabase.createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY) : null;

const I18N = {
 fr:{title:"Trouve les codes. Reste le dernier.",subtitle:"Crée un salon, partage le même lien et joue en temps réel.",nickname:"Pseudo",roomCode:"Code du salon",join:"Rejoindre le salon",how:"Comment jouer",rule1:"Chaque joueur choisit un code secret de 4 chiffres.",rule2:"À ton tour, choisis un joueur et propose 4 chiffres.",rule3:"🟩 bien placé • 🟨 mal placé • ⬜ absent.",rule4:"Si tu trouves le code exact, le joueur ciblé est éliminé.",rule5:"À plus de 2 joueurs, la partie continue jusqu'au dernier joueur restant.",room:"Salon",copyLink:"Copier le lien",lobbyTitle:"Salle d'attente",secret:"Ton code secret (4 chiffres)",ready:"Je suis prêt",start:"Lancer la partie",leave:"Quitter",yourTurn:"À toi de jouer",chooseTarget:"Choisis un adversaire encore en jeu.",guess:"Code à tester",try:"Tester le code",history:"Historique",waiting:"En attente",online:"En ligne",eliminated:"Éliminé",inGame:"En jeu",started:"Partie en cours",finished:"Partie terminée",notYourTurn:"Ce n'est pas ton tour.",needReady:"Tout le monde doit être prêt.",needTwo:"Il faut au moins 2 joueurs.",invalid:"Entre exactement 4 chiffres.",select:"Sélectionne un adversaire.",noSelf:"Tu ne peux pas te cibler.",found:"Code trouvé !",eliminatedYou:"Tu as été éliminé.",winner:"🎉 Victoire !",copied:"Lien copié.",config:"Configure Supabase dans app.js avant de jouer.",joined:"Salon rejoint.",hostOnly:"Seul le créateur peut lancer la partie."},
 en:{title:"Crack the codes. Be the last one standing.",subtitle:"Create a room, share the same link and play in real time.",nickname:"Nickname",roomCode:"Room code",join:"Join room",how:"How to play",rule1:"Each player chooses a secret 4-digit code.",rule2:"On your turn, choose a player and enter 4 digits.",rule3:"🟩 correct place • 🟨 wrong place • ⬜ absent.",rule4:"Find an exact code and that player is eliminated.",rule5:"With more than 2 players, play continues until one player remains.",room:"Room",copyLink:"Copy link",lobbyTitle:"Lobby",secret:"Your secret code (4 digits)",ready:"I'm ready",start:"Start game",leave:"Leave",yourTurn:"Your turn",chooseTarget:"Choose an opponent still in the game.",guess:"Code to test",try:"Test code",history:"History",waiting:"Waiting",online:"Online",eliminated:"Eliminated",inGame:"In game",started:"Game in progress",finished:"Game over",notYourTurn:"It's not your turn.",needReady:"Everyone must be ready.",needTwo:"At least 2 players are required.",invalid:"Enter exactly 4 digits.",select:"Select an opponent.",noSelf:"You cannot target yourself.",found:"Code found!",eliminatedYou:"You have been eliminated.",winner:"🎉 Victory!",copied:"Link copied.",config:"Configure Supabase in app.js before playing.",joined:"Room joined.",hostOnly:"Only the room creator can start the game."},
 es:{title:"Descifra los códigos. Sé el último.",subtitle:"Crea una sala, comparte el mismo enlace y juega en tiempo real.",nickname:"Apodo",roomCode:"Código de sala",join:"Entrar en la sala",how:"Cómo jugar",rule1:"Cada jugador elige un código secreto de 4 cifras.",rule2:"En tu turno, elige un jugador e introduce 4 cifras.",rule3:"🟩 posición correcta • 🟨 posición incorrecta • ⬜ ausente.",rule4:"Si encuentras un código exacto, ese jugador queda eliminado.",rule5:"Con más de 2 jugadores, la partida continúa hasta que quede uno.",room:"Sala",copyLink:"Copiar enlace",lobbyTitle:"Sala de espera",secret:"Tu código secreto (4 cifras)",ready:"Estoy listo",start:"Iniciar partida",leave:"Salir",yourTurn:"Tu turno",chooseTarget:"Elige un rival que siga en juego.",guess:"Código a probar",try:"Probar código",history:"Historial",waiting:"Esperando",online:"En línea",eliminated:"Eliminado",inGame:"En juego",started:"Partida en curso",finished:"Partida terminada",notYourTurn:"No es tu turno.",needReady:"Todos deben estar listos.",needTwo:"Se necesitan al menos 2 jugadores.",invalid:"Introduce exactamente 4 cifras.",select:"Selecciona un rival.",noSelf:"No puedes elegirte a ti mismo.",found:"¡Código encontrado!",eliminatedYou:"Has sido eliminado.",winner:"🎉 ¡Victoria!",copied:"Enlace copiado.",config:"Configura Supabase en app.js antes de jugar.",joined:"Sala unida.",hostOnly:"Solo el creador puede iniciar la partida."},
 nl:{title:"Kraak de codes. Blijf als laatste over.",subtitle:"Maak een kamer, deel dezelfde link en speel live.",nickname:"Bijnaam",roomCode:"Kamercode",join:"Kamer binnengaan",how:"Zo speel je",rule1:"Elke speler kiest een geheime code van 4 cijfers.",rule2:"Kies tijdens je beurt een speler en voer 4 cijfers in.",rule3:"🟩 juiste plek • 🟨 verkeerde plek • ⬜ ontbreekt.",rule4:"Vind je een code exact, dan wordt die speler uitgeschakeld.",rule5:"Met meer dan 2 spelers gaat het spel door tot er één speler overblijft.",room:"Kamer",copyLink:"Link kopiëren",lobbyTitle:"Wachtruimte",secret:"Jouw geheime code (4 cijfers)",ready:"Ik ben klaar",start:"Start spel",leave:"Verlaten",yourTurn:"Jouw beurt",chooseTarget:"Kies een tegenstander die nog in het spel zit.",guess:"Te testen code",try:"Code testen",history:"Geschiedenis",waiting:"Wachten",online:"Online",eliminated:"Uitgeschakeld",inGame:"In het spel",started:"Spel bezig",finished:"Spel afgelopen",notYourTurn:"Je bent nu niet aan de beurt.",needReady:"Iedereen moet klaar zijn.",needTwo:"Er zijn minstens 2 spelers nodig.",invalid:"Voer precies 4 cijfers in.",select:"Kies een tegenstander.",noSelf:"Je kunt jezelf niet kiezen.",found:"Code gevonden!",eliminatedYou:"Je bent uitgeschakeld.",winner:"🎉 Gewonnen!",copied:"Link gekopieerd.",config:"Configureer Supabase in app.js voordat je speelt.",joined:"Kamer geopend.",hostOnly:"Alleen de maker van de kamer kan starten."}
};
let lang = localStorage.getItem("cb_lang") || "fr";
let me=null, room=null, channel=null, selectedTarget=null, players=[];
const $=id=>document.getElementById(id), t=k=>I18N[lang][k]||I18N.fr[k]||k;
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));$("language").value=lang;$("configWarning").textContent=t("config");$("configWarning").classList.toggle("hidden",configured)}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active")}
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function validCode(v){return /^\d{4}$/.test(v)}
function renderPlayers(targetId, game=false){const el=$(targetId);el.innerHTML=players.map(p=>`<div class="player"><span class="name">${escapeHtml(p.nickname)}${p.user_id===me?.id?" (you)":""}</span><span class="status">${p.eliminated?"✖ "+t("eliminated"):game?"● "+t("inGame"):(p.ready?"✓ "+t("ready"):t("waiting"))}</span></div>`).join("")}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function ensureAuth(){if(!sb)throw Error("not configured");let {data,error}=await sb.auth.getSession();if(error)throw error;if(!data.session){let r=await sb.auth.signInAnonymously();if(r.error)throw r.error;me=r.data.user}else me=data.session.user}
async function loadRoom(){let r=await sb.from("rooms").select("*").eq("code",room).single();if(r.error)throw r.error;return r.data}
async function loadPlayers(){let r=await sb.from("players").select("user_id,nickname,ready,eliminated,joined_at").eq("room_id",room.id).order("joined_at");if(r.error)throw r.error;players=r.data||[];renderPlayers("players");renderPlayers("gamePlayers",true);updateControls()}
function updateControls(){let mine=players.find(p=>p.user_id===me.id);if(!mine)return;$("readyBtn").textContent=mine.ready?t("waiting"):t("ready");$("startBtn").classList.toggle("hidden",!(room.host_id===me.id&&room.status==="lobby"));$("secret").disabled=mine.ready;const active=players.filter(p=>!p.eliminated);$("guessPanel").classList.toggle("hidden",room.status!=="playing"||mine.eliminated||active.length<=1)}
async function joinRoom(){
 if(!configured){$("configWarning").classList.remove("hidden");return}
 const nick=$("nickname").value.trim().slice(0,18), code=$("roomCode").value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,12);
 if(!nick||code.length<3){toast("Pseudo + code requis.");return}
 try{await ensureAuth();let rr=await sb.from("rooms").select("*").eq("code",code).maybeSingle();
  if(!rr.data){let ins=await sb.from("rooms").insert({code,host_id:me.id,status:"lobby"}).select().single();if(ins.error)throw ins.error;room=ins.data}
  else room=rr.data;
  let existing=await sb.from("players").select("*").eq("room_id",room.id).eq("user_id",me.id).maybeSingle();
  if(!existing.data){let add=await sb.from("players").insert({room_id:room.id,user_id:me.id,nickname:nick,ready:false,eliminated:false}).select().single();if(add.error)throw add.error}
  else{await sb.from("players").update({nickname:nick}).eq("room_id",room.id).eq("user_id",me.id)}
  $("roomLabel").textContent=room.code;$("gameRoom").textContent=room.code;history.pushState({},'',location.pathname+"?room="+encodeURIComponent(room.code));
  await loadPlayers();subscribe();toast(t("joined"));show(room.status==="lobby"?"lobby":"game");if(room.status==="playing")await refreshGame();else if(room.status==="finished")await refreshGame();
 }catch(e){console.error(e);toast(e.message||"Erreur")}
}
function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel("room-"+room.id).on("postgres_changes",{event:"*",schema:"public",table:"players",filter:"room_id=eq."+room.id},async()=>{await loadPlayers();if(room.status!=="lobby")await refreshGame()}).on("postgres_changes",{event:"*",schema:"public",table:"rooms",filter:"id=eq."+room.id},async()=>{room=await loadRoom();show(room.status==="lobby"?"lobby":"game");await loadPlayers();if(room.status!=="lobby")await refreshGame()}).on("postgres_changes",{event:"INSERT",schema:"public",table:"guesses",filter:"room_id=eq."+room.id},refreshGame).subscribe()}
async function saveSecret(){const s=$("secret").value.trim();if(!validCode(s)){toast(t("invalid"));return false}let r=await sb.rpc("set_secret",{p_room_id:room.id,p_secret:s});if(r.error){toast(r.error.message);return false}return true}
$("readyBtn").onclick=async()=>{let mine=players.find(p=>p.user_id===me.id);if(!mine)return;if(!mine.ready){if(!(await saveSecret()))return;await sb.from("players").update({ready:true}).eq("room_id",room.id).eq("user_id",me.id)}else await sb.from("players").update({ready:false}).eq("room_id",room.id).eq("user_id",me.id);await loadPlayers()}
$("startBtn").onclick=async()=>{if(room.host_id!==me.id){toast(t("hostOnly"));return}if(players.length<2){toast(t("needTwo"));return}if(players.some(p=>!p.ready)){toast(t("needReady"));return}let r=await sb.rpc("start_game",{p_room_id:room.id});if(r.error)toast(r.error.message)}
function selectTarget(id){selectedTarget=id;document.querySelectorAll("#targetButtons button").forEach(b=>b.classList.toggle("selected",b.dataset.id===id))}
async function refreshGame(){room=await loadRoom();await loadPlayers();const mine=players.find(p=>p.user_id===me.id), active=players.filter(p=>!p.eliminated);$("phaseBadge").textContent=room.status==="playing"?t("started"):t("finished");$("winnerBanner").classList.toggle("hidden",room.status!=="finished");if(room.status==="finished"){$("winnerBanner").textContent=active[0]?`${t("winner")} ${active[0].nickname}`:t("finished")}
 const targets=active.filter(p=>p.user_id!==me.id);$("targetButtons").innerHTML=targets.map(p=>`<button data-id="${p.user_id}">${escapeHtml(p.nickname)}</button>`).join("");$("targetButtons").querySelectorAll("button").forEach(b=>b.onclick=()=>selectTarget(b.dataset.id));selectedTarget=targets.find(p=>p.user_id===selectedTarget)?selectedTarget:null;
 let q=await sb.from("guesses").select("*").eq("room_id",room.id).order("created_at",{ascending:false}).limit(80);if(q.error)return;$("history").innerHTML=q.data.map(g=>`<div class="guess-item"><div class="guess-meta"><span>${escapeHtml(g.guesser_name)} → ${escapeHtml(g.target_name)}</span><span>${new Date(g.created_at).toLocaleTimeString()}</span></div><strong>${g.guess}</strong><div class="feedback">${"🟩".repeat(g.exact)}${"🟨".repeat(g.misplaced)}${"⬜".repeat(4-g.exact-g.misplaced)}</div></div>`).join("")||"<p>"+t("waiting")+"</p>";
 $("guessBtn").disabled=room.status!=="playing"||mine.eliminated||active.length<=1;
}
$("guessBtn").onclick=async()=>{const g=$("guess").value.trim();if(!validCode(g)){toast(t("invalid"));return}if(!selectedTarget){toast(t("select"));return}let r=await sb.rpc("submit_guess",{p_room_id:room.id,p_target_id:selectedTarget,p_guess:g});if(r.error){toast(r.error.message);return}const result=r.data?.[0];$("guess").value="";if(result?.eliminated){toast(t("found"))}await refreshGame()}
$("copyLink").onclick=async()=>{await navigator.clipboard.writeText(location.href);toast(t("copied"))}
$("leaveLobby").onclick=$("leaveGame").onclick=async()=>{if(room&&me)await sb.from("players").delete().eq("room_id",room.id).eq("user_id",me.id);location.href=location.pathname}
$("joinBtn").onclick=joinRoom;
$("language").onchange=e=>{lang=e.target.value;localStorage.setItem("cb_lang",lang);applyLang()}
applyLang();
const qs=new URLSearchParams(location.search);if(qs.get("room"))$("roomCode").value=qs.get("room");
